[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

[target.x86_64-apple-darwin]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.aarch64-apple-darwin]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.x86_64-pc-windows-msvc]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.i686-pc-windows-msvc]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.aarch64-pc-windows-msvc]
rustflags = [ "-C", "target-feature=+crt-static" ]